#!/bin/sh

# Nintendo DS images played with desmume
# Usage: ds [-l|-g] <gamepat>
# gamepat may be substring or glob pattern
# if more than one match, pops up selection dialog or just lists matches if -l
# if no gamepat, lists all games or pops up selection dialog if -g

gamesdir=("$HOME/games/ds")
ext=(nds)

. /usr/local/share/img-game.sh

# --3d-engine=2 only in gtk (requires work to implement in sdl)
# --side-by-side is my own option, sdl only (gtk does it using cairo)
# --opengl-2d is sdl only (gtk uses cairo)
# ROMs are available here, but I don't think they're necessary
#desmume --3d-engine=2 --load-type=1 --cpu-mode=1 --num-cores=4 --bios-arm9=$dsdir/bios/biosnds9.rom --bios-arm7=$dsdir/bios/biosnds7.rom --bios-swi=1 "$@" "$df" >/dev/null &
exec desmume --3d-engine=2 --load-type=1 --cpu-mode=1 --num-cores=4 "$@" "$df" >/dev/null &
#desmume-cli --opengl-2d --side-by-side --load-type=1 --cpu-mode=1 --num-cores=4 "$@" "$df" >/dev/null &
