#!/bin/sh

# GBA, GBC, GB, etc images played with VBA-M
# Usage: gb [-l|-g] <gamepat>
# gamepat may be substring or glob pattern
# if more than one match, pops up selection dialog or just lists matches if -l
# if no gamepat, lists all games or pops up selection dialog if -g


gamesdir=("$HOME/games/gba" "$HOME/games/gb")
ext=(gb gbc gba gb.gz gbc.gz gba.gz)

. /usr/local/share/img-game.sh

exec vbam -F "$df" "$@"
#wxvbam -f "$df" "$@"
