#!/bin/sh

# Playstation games:  psx <gamepat> [-cfg]
# gamepat may be substring or glob pattern
# -cfg invokes GUI w/o CD for per-game config; run pcsxr itself for default

#gamesdir="$HOME/games/psx"
gamesdir=/ovf/psx
confdir="$HOME/.pcsxr"

game="$1"

# mdf->mds
# img->ccd +sub
# bin->cue (requires editing)
# iso standalone (some .bins as well)

if [ -z "$game" ]; then
	( cd "$gamesdir"; ls -C *.{bin,img,mdf,iso} | sed 's/\.[^.]*$//' )
	exit 0
fi

shift

if [ ! -d "$confdir/plugins" -o ! -f "$confdir/pcsxr.cfg" ]; then
	echo "Configure pcsxr once first!"
	exit 1
fi

b="${game##*/}"
b="${b%.*}"
bb="${b%-[1-9]}"
if [ -f "$game" ]; then
   df="$game"
else
   # try to find given name directly
   df="$gamesdir/$b"
   for x in bin img mdf iso; do
     test -f "$df".$x && break
   done
   df="$df".$x
   if [ ! -f "$df" ]; then
        # and if that fails, try pattern matching
	bop=\*; eop=\*
	case "$game" in
	  '^'*'$') bop=; eop=; game="${game#^}"; game="${game%\$}" ;;
	  '^'*) bop=; game="${game#^}" ;;
	  *'$') eop=; game="${game%\$}" ;;
	esac
	g="` cd \"\$gamesdir\"; ls -C *.{bin,img,mdf,iso} | sed 's/\.[^.]*$//' | \
	       while read g; do
	          case "\$g" in
		     $bop$game$eop) echo \"\$g\" ;;
		   esac
	       done`"
        if [ -n "$g" ]; then
	   nl=$(echo "$g" | wc -l)
	   if [ $nl -gt 1 ]; then
	      echo "More than one match:"
	      echo "$g"
	      exit 0
	    fi
	    df="$gamesdir/$g"
	    for x in bin img mdf iso; do
	       test -f "$df".$x && break
	     done
	     df="$df".$x
	     b="${df##*/}"
	     b="${b%.*}"
	     bb="${b%-[1-9]}"
	fi
   fi
   test -f "$df" || exit 1
fi
# Now the game is known; make per-game config
mkdir -p "$confdir/games/$bb"
(
	cd "$confdir/games/$bb"
	ln -s ../../plugins/* . 2>/dev/null
	test -f pcsxr.cfg || \
	   sed -e "s%^\(Mcd\([12]\)\).*%\1 = $confdir/memcards/$bb\2.mcd%" \
	       -e "s%.pcsxr/plugins%.pcsxr/games/$bb%" \
	          ../../pcsxr.cfg > pcsxr.cfg
)
# -cfg option to set per-game config
if [ "x-cfg" = "x$1" ]; then
        # convert soft links to files to avoid overwriting global config
	cd "$confdir/games/$bb"
	find -name \*.cfg -type l | while read x; do
		rm -f $x
		cp ../../plugins/$x .
	done
	# when done, convert files identical to global config back to links
	trap '
	find -name \*.cfg -type f | while read x; do
		cmp $x ../../plugins/$x >/dev/null 2>&1 && ln -sf ../../plugins/$x .
	done
	' 0
	pcsxr -cfg games/"$bb"/pcsxr.cfg
else
	# used to use "taksset 1", but I'm not sure it's needed
	exec pcsxr -cfg games/"$bb"/pcsxr.cfg -psxout -cdfile "$df" "$@"
fi
