#!/bin/sh
pid=
nl=`wc -l /tmp/.last-game 2>/dev/null | cut -d\  -f1`
if [ ${nl:-0} -eq 2 ]; then
  pid=`head -n 1 /tmp/.last-game`
  ps -p $pid >/dev/null || pid=
fi
if [ -z "$pid" ]; then
  notify-send "Restore Game Failed" "No savable game running"
  exit 1
fi
notify-send "Restored Game" "$(`tail -n 1 /tmp/.last-game` -r auto)"
