#!/bin/sh
ext=
if [ x-e = "x$1" ]; then
  ext="$2"; shift 2
fi
wineserver"$ext" -k
wineserver"$ext" -f -p0 & pid=$!
trap "wineserver$ext -k" 0
if [ -z "$WINEARCH" ]; then
   a=`head -n 5 "$WINEPREFIX"/user.reg 2>/dev/null | grep '^#arch=' | cut -d= -f2`
   test -n "$a" && export WINEARCH="$a"
fi
if [ win64 = "$WINEARCH" ]; then
  wine64"$ext" "$@"
else
  wine"$ext" "$@"
fi
wait $pid
